version: "4.15"

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FactoryModel
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local