// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserData.DataAccess;

#nullable disable

namespace UserData.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserData.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30b01a1d-2163-4655-87e1-30315b5b00a4"),
                            DisplayName = "Ivan Ivanov",
                            Email = "i.ivanov@example.com",
                            UserName = "ivivan"
                        },
                        new
                        {
                            Id = new Guid("f2f55f46-f9d8-4087-9b14-e39e7495a8d3"),
                            DisplayName = "Ivelina Georgieva",
                            Email = "i.georgieva@example.com",
                            UserName = "igeor"
                        },
                        new
                        {
                            Id = new Guid("62b0cfc8-722c-40c0-ab08-991b61d78d57"),
                            DisplayName = "Katerina Ivanova",
                            Email = "k.ivanova@example.com",
                            UserName = "kivanova"
                        },
                        new
                        {
                            Id = new Guid("87c84637-7e69-4c0a-94bd-7e09921fddaf"),
                            DisplayName = "Ivaila Gerdjikova",
                            Email = "i.gerdjikova@example.com",
                            UserName = "igerd"
                        },
                        new
                        {
                            Id = new Guid("52026104-2418-42c3-8891-28c75abb4a2f"),
                            DisplayName = "Kaloqn Kostadinov",
                            Email = "k.kostadinov@example.com",
                            UserName = "kakost"
                        },
                        new
                        {
                            Id = new Guid("3f987a11-15c2-4b75-8ff3-6955be5ba91a"),
                            DisplayName = "Georgi Dimitrov",
                            Email = "g.dimitrov@example.com",
                            UserName = "gdimit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
